# Generated by Django 5.2.5 on 2025-09-05 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(default=22)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(null=True, upload_to='images/%y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report', models.CharField(blank=True, max_length=255, null=True)),
                ('file_report', models.FileField(null=True, upload_to='files/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='unv_card',
            fields=[
                ('expir_date', models.DateField(auto_now=True)),
                ('prod_date', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('General', 'General'), ('Finincial', 'Finincial')], max_length=9)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('loc', models.TextField()),
                ('add', models.CharField(max_length=70)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
