# Generated by Django 5.2.5 on 2025-09-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(default=22)),
                ('salary', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('image', models.ImageField(null=True, upload_to='images/%y/%m/%d')),
                ('report', models.CharField(blank=True, max_length=255, null=True)),
                ('file_report', models.FileField(null=True, upload_to='files/%y/%m/%d/')),
            ],
        ),
    ]
